#!/bin/sh
set -e

#DEBHELPER#

PKG=wg-burnmaster

case "$1" in
  configure)
        test -x /usr/sbin/update-initramfs && update-initramfs -u
        test -x /usr/sbin/update-initramfs && update-initramfs -u -k 3.4.28.rt40-1-pr2-rt

    ;;
  
  *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac
